require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/expo-modules-core/scripts/native_modules'

platform :ios, '13.4'
install! 'cocoapods', :deterministic_uuids => false

target 'talksy' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Firebase Pods
  pod 'Firebase', :tag => '10.22.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

  target 'talksyTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end
  end
end